In [1]:
import pandas as pd

In [2]:
l = [1,2,3,4,5,1,4,9,16,25]

In [3]:
pd.DataFrame(l, columns= ["degisken"])

degisken
0         1
1         2
2         3
3         4
4         5
5         1
6         4
7         9
8        16
9        25

In [5]:
import numpy as np
m = np.arange(1,25 ).reshape(6,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [8]:
veri = pd.DataFrame(m, columns= ["veri1","veri2","veri3","veri4"])
veri

veri1  veri2  veri3  veri4
0      1      2      3      4
1      5      6      7      8
2      9     10     11     12
3     13     14     15     16
4     17     18     19     20
5     21     22     23     24

In [9]:
veri.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [10]:
df = veri
df

veri1  veri2  veri3  veri4
0      1      2      3      4
1      5      6      7      8
2      9     10     11     12
3     13     14     15     16
4     17     18     19     20
5     21     22     23     24

In [12]:
df.head(2)

veri1  veri2  veri3  veri4
0      1      2      3      4
1      5      6      7      8

In [13]:
df.columns = ("deg1","deg2","deg3","deg4")
df

deg1  deg2  deg3  deg4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20
5    21    22    23    24

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
len(df)

6

In [17]:
df.shape

(6, 4)

In [18]:
df.ndim

2

In [22]:
df.axes

[RangeIndex(start=0, stop=6, step=1),
 Index(['deg1', 'deg2', 'deg3', 'deg4'], dtype='object')]

In [23]:
df.size

24

In [24]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
type(df.values)

numpy.ndarray