<h1>Numpy</h1>

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 6])

In [4]:
a * b

array([ 2,  6, 12, 20, 30])

In [5]:
type(a)

numpy.ndarray

In [6]:
[6, 7.5,8]

[6, 7.5, 8]

In [9]:
np.array([6, 7.5, 8 ])


array([6. , 7.5, 8. ])

In [10]:
np.array([6, 7.5, 8 ], dtype="int32")


array([6, 7, 8])

In [11]:
np.array([6, 7.5, 8 ], dtype="float")


array([6. , 7.5, 8. ])

In [17]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((3, 2, 5), dtype=int)


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [25]:
np.full((3,3), 5, dtype=int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [26]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [27]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
np.arange(1,22,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [32]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
np.linspace(0,10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [42]:
np.random.normal(10, 2, (10,5))

array([[ 9.29805368,  7.71207052,  6.67665657,  9.14376526,  8.56143362],
       [ 7.48635057, 12.41725821, 11.82006898,  9.96134022, 16.29210025],
       [ 6.79513061,  8.65570725, 11.87549952,  5.84893915, 11.8758215 ],
       [ 8.59561605, 12.429247  , 11.89384074, 10.47668409,  6.42843842],
       [ 8.48980225, 13.83345372, 10.76979856, 14.4118213 ,  5.38989929],
       [11.96979973,  6.09716129, 10.21078588,  8.20852138, 10.46729823],
       [10.33104791, 10.11508532,  9.26056365, 11.23895682,  6.39021892],
       [ 7.34639892, 11.35341869, 12.20200516,  9.97233684, 10.36175447],
       [ 9.02715249,  9.61774339,  9.52659172, 14.24474646, 12.59078631],
       [ 7.39447164,  9.22995165,  5.75655682, 11.3515727 , 10.77252728]])

In [51]:
np.random.randint(1 ,11, (5,5))

array([[ 9, 10,  8,  4,  9],
       [ 8,  3, 10,  1,  8],
       [ 2, 10, 10,  7,  6],
       [ 7,  3,  9,  9,  8],
       [ 2,  4,  7,  4,  7]])