Özellikler
<ul  type="square">
    <li>
        <bold>ndim: </bold>boyut sayısı
    </li>
    <li>
        <bold>shape: </bold>boyut bilgisi
    </li>
    <li>
        <bold>size: </bold>toplam eleman sayısı
    </li>
    <li>
        <bold>dtype: </bold>array veeri tipi
    </li>
</ul>


In [1]:
import numpy as np

In [2]:
np.random.randint(10, size=10)

array([3, 9, 2, 5, 0, 8, 7, 0, 5, 5])

In [3]:
a = np.random.randint(10, size=10)

In [4]:
a

array([4, 9, 9, 7, 0, 1, 5, 0, 9, 2])

In [5]:
a.ndim

1

In [6]:
a.shape

(10,)

In [7]:
type(a)

numpy.ndarray

In [8]:
a.size

10

In [9]:
a.dtype

dtype('int32')

In [13]:
b = np.random.randint(1,7, (7,5))

In [14]:
b

array([[4, 2, 1, 6, 1],
       [2, 5, 2, 6, 3],
       [1, 2, 3, 4, 3],
       [6, 4, 4, 6, 6],
       [3, 3, 3, 4, 5],
       [4, 1, 2, 5, 1],
       [3, 5, 5, 6, 2]])

In [15]:
b.ndim

2

In [16]:
b.shape

(7, 5)

In [17]:
b.size

35

In [18]:
b.dtype

dtype('int32')