In [1]:
import numpy as np

In [2]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.reshape(np.arange(1,10), (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1, 10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
on = np.arange(1, 25)

In [11]:
on.ndim

1

In [12]:
on.size

24

In [13]:
on.reshape((6,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
on.reshape((2,3,2,2))

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [15]:
on.reshape((2,3,2,2)).ndim

4

In [17]:
on.reshape((2,3,2,2)).shape

(2, 3, 2, 2)

In [18]:
on.reshape((2,3,2,2)).size

24