In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [3]:
np.concatenate([x, y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.concatenate([y, x])

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [5]:
z = np.array([11,12,13,14,15])

In [6]:
np.concatenate([x, y, z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])


In [17]:
a ,b 


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [18]:
np.concatenate([a ,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
np.concatenate([a ,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.concatenate([a ,b], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])