In [21]:
import numpy as np

In [22]:
x = np.random.randint(10,99, 24)
x

array([77, 69, 11, 58, 89, 31, 18, 96, 95, 45, 18, 74, 63, 62, 16, 45, 51,
       77, 49, 72, 29, 88, 79, 88])

In [23]:
y = np.split(x, [8,16])
y

[array([77, 69, 11, 58, 89, 31, 18, 96]),
 array([95, 45, 18, 74, 63, 62, 16, 45]),
 array([51, 77, 49, 72, 29, 88, 79, 88])]

In [24]:
y[0].sum(), y[1].sum(), y[2].sum()

(449, 418, 533)

In [28]:
a ,b, c = np.split(x, [8,16])
a

array([77, 69, 11, 58, 89, 31, 18, 96])

In [29]:
b, c

(array([95, 45, 18, 74, 63, 62, 16, 45]),
 array([51, 77, 49, 72, 29, 88, 79, 88]))

iki boyutlu ayırma

In [31]:
m = np.arange(24).reshape(6,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [35]:
ust, alt = np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
np.hsplit(m, [1])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]])]