In [8]:
import numpy as np

In [9]:
v = np.random.randint(1,100,50)
v

array([59,  1, 87, 96,  8, 89, 85,  1, 84, 84, 39, 91, 21, 13,  6, 59, 65,
       30, 95, 47, 32, 82, 63, 46, 63, 47,  7, 27, 38, 84,  6, 82, 70, 18,
       18, 95, 56, 18, 63, 99,  9, 44, 47, 19,  5, 22, 82, 88, 44, 70])

In [10]:
np.sort(v)

array([ 1,  1,  5,  6,  6,  7,  8,  9, 13, 18, 18, 18, 19, 21, 22, 27, 30,
       32, 38, 39, 44, 44, 46, 47, 47, 47, 56, 59, 59, 63, 63, 63, 65, 70,
       70, 82, 82, 82, 84, 84, 84, 85, 87, 88, 89, 91, 95, 95, 96, 99])

In [11]:
v

array([59,  1, 87, 96,  8, 89, 85,  1, 84, 84, 39, 91, 21, 13,  6, 59, 65,
       30, 95, 47, 32, 82, 63, 46, 63, 47,  7, 27, 38, 84,  6, 82, 70, 18,
       18, 95, 56, 18, 63, 99,  9, 44, 47, 19,  5, 22, 82, 88, 44, 70])

In [12]:
v.sort()

In [13]:
v

array([ 1,  1,  5,  6,  6,  7,  8,  9, 13, 18, 18, 18, 19, 21, 22, 27, 30,
       32, 38, 39, 44, 44, 46, 47, 47, 47, 56, 59, 59, 63, 63, 63, 65, 70,
       70, 82, 82, 82, 84, 84, 84, 85, 87, 88, 89, 91, 95, 95, 96, 99])

In [14]:
m = np.random.normal(20,5, (3,3))
m

array([[24.00029547, 14.60870984, 31.45684379],
       [25.61658135, 19.7518797 , 18.31396797],
       [22.69096474, 22.52727558, 16.25356116]])

In [15]:
np.sort(m)

array([[14.60870984, 24.00029547, 31.45684379],
       [18.31396797, 19.7518797 , 25.61658135],
       [16.25356116, 22.52727558, 22.69096474]])

In [17]:
np.sort(m, axis=0)

array([[22.69096474, 14.60870984, 16.25356116],
       [24.00029547, 19.7518797 , 18.31396797],
       [25.61658135, 22.52727558, 31.45684379]])