In [ ]:
import numpy as np

In [13]:
a = np.random.randint(10, size = 10)
a

array([9, 7, 4, 2, 2, 7, 3, 8, 5, 9])

In [14]:
a[0]

9

In [15]:
a[0] = 7
a

array([7, 7, 4, 2, 2, 7, 3, 8, 5, 9])

In [16]:
m = np.random.randint(10, size = (4, 3))
m


array([[5, 1, 0],
       [2, 8, 6],
       [4, 3, 8],
       [5, 3, 6]])

In [21]:
m[2, 1]

3

In [28]:
m[2][1] = 13.5
m

array([[ 5,  1,  0],
       [ 2,  8,  6],
       [ 4, 13,  8],
       [ 5,  3,  6]])