In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[0:3]

array([20, 21, 22])

In [4]:
a[:3]

array([20, 21, 22])

In [10]:
a[2::-1]

array([22, 21, 20])

In [11]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [13]:
a[1::3]

array([21, 24, 27])

In [15]:
m = np.random.randint(1,7, size=(5,5))
m

array([[1, 5, 6, 4, 3],
       [3, 5, 4, 3, 1],
       [6, 2, 1, 2, 5],
       [3, 3, 2, 2, 2],
       [3, 3, 2, 4, 1]])

In [17]:
m[0]

array([1, 5, 6, 4, 3])

In [16]:
m[:,0]

array([1, 3, 6, 3, 3])

In [19]:
m[0:1]

array([[1, 5, 6, 4, 3]])

In [25]:
m[1:3, 1:4 ]

array([[5, 4, 3],
       [2, 1, 2]])

In [29]:
m[::-1, 1:3:]

array([[3],
       [3],
       [2],
       [5],
       [5]])