In [11]:
import numpy as np

In [12]:
a = np.random.randint(10, size=(5,5))
a

array([[5, 5, 3, 7, 8],
       [2, 6, 5, 2, 5],
       [2, 4, 1, 0, 5],
       [4, 4, 0, 5, 7],
       [7, 6, 7, 5, 1]])

In [13]:
alt_a = a[0:3,0:2]
alt_a

array([[5, 5],
       [2, 6],
       [2, 4]])

In [14]:
alt_a [0,0] = 12345
alt_a [1,1] = 54321
alt_a

array([[12345,     5],
       [    2, 54321],
       [    2,     4]])

In [15]:
a

array([[12345,     5,     3,     7,     8],
       [    2, 54321,     5,     2,     5],
       [    2,     4,     1,     0,     5],
       [    4,     4,     0,     5,     7],
       [    7,     6,     7,     5,     1]])

In [16]:
m = np.random.randint(10, size=(5,5))
m

array([[5, 3, 9, 9, 2],
       [1, 1, 1, 2, 6],
       [6, 6, 4, 1, 8],
       [7, 8, 6, 6, 9],
       [8, 9, 2, 1, 1]])

In [19]:
alt_m = m[0:3, 0:2].copy()
alt_m

array([[5, 3],
       [1, 1],
       [6, 6]])

In [20]:
alt_m[0,0] = 5555
alt_m[1,1] = 5555
alt_m

array([[5555,    3],
       [   1, 5555],
       [   6,    6]])

In [21]:
m

array([[5, 3, 9, 9, 2],
       [1, 1, 1, 2, 6],
       [6, 6, 4, 1, 8],
       [7, 8, 6, 6, 9],
       [8, 9, 2, 1, 1]])