In [1]:
import numpy as np

In [2]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
v > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
v[v>5]

array([6, 7, 8, 9])

In [5]:
v[v <= 5]

array([0, 1, 2, 3, 4, 5])

In [6]:
v *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
v **v

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])