In [1]:
import numpy as np

In [2]:
v = np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [3]:
v - 1

array([0, 1, 2, 3, 4])

In [4]:
v * 5

array([ 5, 10, 15, 20, 25])

ufunc

In [5]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [6]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [7]:
np.multiply(v, 5)

array([ 5, 10, 15, 20, 25])

In [9]:
np.divide(v, 5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [11]:
np.power(v, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [12]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [14]:
np.absolute([-5,-4,-3,-2,-1])

array([5, 4, 3, 2, 1])

In [17]:
np.absolute(np.array([-5,-4,-3,-2,-1] ))

array([5, 4, 3, 2, 1])

In [21]:
np.sin(360)

0.9589157234143065

In [22]:
np.cos(360)

-0.2836910914865273

In [23]:
v = np.arange(1,10)
v

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [25]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [26]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

?np *cheatsheet*