In [6]:
import numpy as np
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [10]:
np.zeros((2,3)).ndim

2

In [12]:
np.random.randint(1,10, (3,3,2,3))

array([[[[1, 7, 3],
         [2, 3, 5]],

        [[5, 9, 2],
         [1, 7, 7]],

        [[1, 2, 6],
         [2, 1, 5]]],


       [[[4, 1, 6],
         [8, 2, 4]],

        [[2, 8, 9],
         [6, 3, 4]],

        [[7, 1, 7],
         [3, 4, 1]]],


       [[[5, 6, 2],
         [1, 4, 6]],

        [[3, 8, 1],
         [4, 1, 4]],

        [[9, 6, 6],
         [1, 5, 6]]]])

In [13]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [14]:
5*np.array([1, 2, 3])

array([ 5, 10, 15])

In [17]:
import numpy as np
5*np.array([1,2,3])

array([ 5, 10, 15])

In [18]:
import numpy as np
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [19]:
import numpy as np
v = np.array([2, 1, 4, 3, 5])
np.sort(v)

array([1, 2, 3, 4, 5])

In [20]:
import numpy as np
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])
v[-2]

9

In [21]:
v[-2:]

array([9, 2])

In [22]:
a = np.array([[4, 7, 4, 5, 9],
[2, 5, 0, 7, 7],
[1, 9, 0, 8, 2]])
a

array([[4, 7, 4, 5, 9],
       [2, 5, 0, 7, 7],
       [1, 9, 0, 8, 2]])

In [24]:
a[1,1]

5

In [23]:
a[1][1]

5

In [25]:
a[0:1]

array([[4, 7, 4, 5, 9]])

In [26]:
a = np.array([[4, 7, 4, 5, 9],
[2, 5, 0, 7, 7],
[1, 9, 0, 8, 2]])

In [28]:
a[:,2]

array([4, 0, 0])

In [30]:
v[1],v[3]

(3, 7)

In [31]:
print(v[1],v[3])

3 7


In [32]:
[v[1],v[3]]

[3, 7]

In [33]:
import numpy as np
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])
 
v[[1,2,3]]

array([3, 6, 9])